name: Feature Request
description: Request a new feature or improvement to an existing feature.
body:
  - type: markdown
    attributes:
      value: "# Feature Request"
  - type: textarea
    id: feature
    attributes:
      label: What feature would you like to suggest?
      description: Please provide as much detail as possible. What would you like to see added or changed?
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Additional Information
      description: Is there anything else we should know?
    validations:
      required: false
